version: "3.7"

services:
  fhir:
    container_name: hapifhir
    image: hapiproject/hapi:v5.0.0
    networks:
      - fhir-benchmark
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/data/hapi/application.yml
      - hapi-data:/data/hapi
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
      
    depends_on:
      - db

  db:
    container_name: hapidb
    image: postgres:12.4-alpine
    restart: always
    networks:
      - fhir-benchmark
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

volumes:
  hapi-data: {}

networks:
  fhir-benchmark:
    external: true
    name: fhir-benchmark