version: "3.9"

services:
  ibm-fhir-server:
    # fhir_ibm_version currently equals 4.5.3
    image: ibmcom/ibm-fhir-server:${IBM_FHIR_SERVER_VERSION}
    networks:
      - fhir-benchmark
    volumes:
      - ./server.xml:/opt/ol/wlp/usr/servers/fhir-server/server.xml
      - ./fhir-server-config.json:/opt/ol/wlp/usr/servers/fhir-server/config/default/fhir-server-config.json
      - ./ping:/opt/ol/wlp/usr/servers/fhir-server/ping
    ports:
      - 9080:9080
      - 9443:9443
    env_file:
      - .env
    depends_on:
      - postgres
      - ibm-fhir-schematool
    user: root
    command: sh -c "
      while ./ping -c1 ibm-fhir-schematool &>/dev/null; do sleep 1; done;
      /opt/ol/wlp/bin/server run fhir-server"

  ibm-fhir-schematool:
    image: ibmcom/ibm-fhir-schematool:${IBM_FHIR_SERVER_VERSION}
    volumes:
      - ./wait-for-it.sh:/opt/schematool/wait-for-it.sh
    depends_on:
      - postgres
    entrypoint: sh -c "
      chmod +x wait-for-it.sh;
      ./wait-for-it.sh postgres:5432 -- ./run.sh --tool.behavior=onboard --db.type=postgresql --db.host=postgres --db.port=5432 --db.database=${POSTGRES_DB} --schema.name.fhir=${POSTGRES_DB_SCHEMA} --user=${POSTGRES_USER} --password=${POSTGRES_PASSWORD}"

  postgres:
    # postgres_version currently equals 13.0
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      # data/postgres folder within the container!
      PGDATA: /data/postgres
      # CHANGE User-Access data for productive usage!
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Using volumes instead of binding local folders, as Windows-based hosts issue a "wrong ownership" error for local folders.
      # Be careful when changing this property for running instances!
      # You might have to copy contents of the data/postgres folder into the volume.
    volumes:
      - ibm-fhir-server-postgres-data:/data/postgres

volumes:
  ibm-fhir-server-postgres-data: {}

networks:
  fhir-benchmark:
    external: true
    name: fhir-benchmark