version: '3.2'
services:
  blaze:
    container_name: blaze
    image: "samply/blaze:0.10.0-alpha.5"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    networks:
      - fhir-benchmark

volumes:
  blaze-data:

networks:
  fhir-benchmark:
    external: true
    name: fhir-benchmark
